#!/bin/sh

# Unlike most *-config scripts, guile-config executes through the
# native Guile interpreter. We could probably get away with using the
# build system version if it didn't output -L/usr/lib. We can use
# strings to extract the link/compile values from the native library
# instead. Hacky but more accurate.

STRINGS="${CHOST}-strings"
LIB="${CB_SYSROOT}usr/lib/libguile.so"

case "$1" in
	link)
		echo -n "-lguile "
		"${STRINGS}" "${LIB}" | grep -F -x -m1 -A1 LIBS | tail -n1 | tr -d "\n"
		"${STRINGS}" "${LIB}" | grep -F -x -m1 -A1 CFLAGS | tail -n1 ;;
	compile)
		"${STRINGS}" "${LIB}" | grep -F -x -m1 -A1 CFLAGS | tail -n1 ;;
	*)
		exec /usr/bin/guile-config "${@}" ;;
esac
